version: 2.1

parameters:
  run-web:
    type: boolean
    default: false

jobs:
  build-web:
    # Build node project
    docker:
      - image: cimg/node:20.12.2
    working_directory: ~/project/web
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          name: Restore npm cache
          keys:
            - node-deps-v1-{{ checksum "package-lock.json" }}
            - node-deps-v1-
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          name: Save npm cache
          key: node-deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus out ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
      - persist_to_workspace:
          root: .
          paths:
            - out

  deploy-web:
    docker:
      - image: cimg/node:20.12.2
    working_directory: ~/project/web
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          name: Restore npm cache
          keys:
            - node-deps-v1-{{ checksum "package-lock.json" }}
            - node-deps-v1-
      - run:
          name: Install packages
          command: npm install
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Cloudflare Pages
          command: npx wrangler pages deploy out --project-name zeus --branch main


workflows:
  web:
    when: << pipeline.parameters.run-web >>
    jobs:
      - build-web
      - deploy-web:
          requires:
            - build-web
          filters:
            branches:
              only: main
